# Laboratorio: Análisis de Datos con Python


## Parte 1: Numpy:

### PROBLEMA NO.1
¿Cuál es el tamaño en bytes de un array de 1000
elementos de tipo booleano?


In [9]:
import numpy as np
import random

list=[]

list_=[True,False]

for i in range(1000):

    val_1=random.choice(list_)

    list.append(val_1)

array_bool=np.array(list)

print(f"El tamaño del array es de {array_bool.nbytes} bytes")




El tamaño del array es de 1000 bytes


### PROBLEMA NO.2


Cree un array cuyos elementos sean los enteros pares en
[1,100] y en orden decreciente. Muestre los 10 últimos
por pantalla.

In [37]:
import numpy as np

list_ej2=[]

for i in range(1,1001):

    list_ej2.append(i)

array_list=np.array(list_ej2)

array_list[-10:]

array([ 991,  992,  993,  994,  995,  996,  997,  998,  999, 1000])

### PROBLEMA NO.3

Dado el array


2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1

Seleccione con una instrucción el subarray de elementos

0 3 7 4

Después, seleccione el subarray de elementos

2 5

8 5


In [60]:
import numpy as np

array_ej3=np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])

print(array_ej3)

print("\n")

print(array_ej3[1,:])

print("\n")

array_1=array_ej3[[0,2],:][:,[0,2]]

print(array_1)


[[2 4 5 6]
 [0 3 7 4]
 [8 8 5 2]
 [1 5 6 1]]


[0 3 7 4]


[[2 5]
 [8 5]]


### PROBLEMA NO.4

Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b).




In [66]:
a=np.array([1,4,2,7])
b=np.array([1,3,2,9])

c=a-b
print(c)

media_=np.mean(c, axis=None, dtype=float)

print(media_)

[ 0  1  0 -2]
-0.25


### PROBLEMA NO.5


Tengo valores de cordenadas (x, y) en las columna del array

1.33 4.5

30.0 10.7

70.2 0.5

Agregue a este array las coordenadas (37.1, -3.6).

Muestre en pantalla las dimensiones del nuevo
array.

In [79]:
array_1=np.array([[1.33,4.5],[30,10.7],[70.2,0.5]])

row = np.array([37.1,-3.6])
row_n = 0 ##row
arr = np.insert(array_1,row_n,[row],axis= 0)

print(arr)

dim_=np.shape(array_1)
print("\n")

print(dim_)


[[37.1  -3.6 ]
 [ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]]


(3, 2)



### PROBLEMA NO.6

Copie el array del ejercicio anterior. Traspóngalo (.
Agregue ahora dos nuevos pares de coordenadas: (10.8,
3.0) y (35.8, 12.0)

In [85]:

trans_=np.transpose(arr)
print(trans_)
print("\n")

column_1 = np.array([10.8,3.0])
column_n = arr.shape[1]+2 # la ultima columna
trans_= np.insert(trans_,column_n,[column_1],axis= 1)

column_2 = np.array([35.8,12.0])
column_n = arr.shape[1]+2 # la ultima columna
trans_ = np.insert(trans_,column_n,[column_2],axis= 1)

print(trans_)

[[37.1   1.33 30.   70.2 ]
 [-3.6   4.5  10.7   0.5 ]]


[[37.1   1.33 30.   70.2  35.8  10.8 ]
 [-3.6   4.5  10.7   0.5  12.    3.  ]]
