# Laboratorio: Análisis de Datos con Python


## Parte 1: Numpy:

In [87]:
import numpy as np
import random

### PROBLEMA NO.1
¿Cuál es el tamaño en bytes de un array de 1000
elementos de tipo booleano?


In [88]:


list=[]

list_=[True,False]

for i in range(1000):

    val_1=random.choice(list_)

    list.append(val_1)

array_bool=np.array(list)

print(f"El tamaño del array es de {array_bool.nbytes} bytes")




El tamaño del array es de 1000 bytes


### PROBLEMA NO.2


Cree un array cuyos elementos sean los enteros pares en
[1,100] y en orden decreciente. Muestre los 10 últimos
por pantalla.

In [89]:
list_ej2=[]

for i in range(1,1001):

    list_ej2.append(i)

array_list=np.array(list_ej2)

array_list[-10:]

array([ 991,  992,  993,  994,  995,  996,  997,  998,  999, 1000])

### PROBLEMA NO.3

Dado el array


2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1

Seleccione con una instrucción el subarray de elementos

0 3 7 4

Después, seleccione el subarray de elementos

2 5

8 5


In [90]:
array_ej3=np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])

print(array_ej3)

print("\n")

print(array_ej3[1,:])

print("\n")

array_1=array_ej3[[0,2],:][:,[0,2]]

print(array_1)


[[2 4 5 6]
 [0 3 7 4]
 [8 8 5 2]
 [1 5 6 1]]


[0 3 7 4]


[[2 5]
 [8 5]]


### PROBLEMA NO.4

Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b).




In [91]:
a=np.array([1,4,2,7])
b=np.array([1,3,2,9])

c=a-b
print(c)

media_=np.mean(c, axis=None, dtype=float)

print(media_)

[ 0  1  0 -2]
-0.25


### PROBLEMA NO.5


Tengo valores de cordenadas (x, y) en las columna del array

1.33 4.5

30.0 10.7

70.2 0.5

Agregue a este array las coordenadas (37.1, -3.6).

Muestre en pantalla las dimensiones del nuevo
array.

In [92]:
array_1=np.array([[1.33,4.5],[30,10.7],[70.2,0.5]])

row = np.array([37.1,-3.6])
row_n = 0 ##row
arr = np.insert(array_1,row_n,[row],axis= 0)

print(arr)

dim_=np.shape(array_1)
print("\n")

print(dim_)


[[37.1  -3.6 ]
 [ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]]


(3, 2)



### PROBLEMA NO.6

Copie el array del ejercicio anterior. Traspóngalo (.
Agregue ahora dos nuevos pares de coordenadas: (10.8,
3.0) y (35.8, 12.0)

In [93]:

trans_=np.transpose(arr)
print(trans_)
print("\n")

column_1 = np.array([10.8,3.0])
column_n = arr.shape[1]+2 # la ultima columna
trans_= np.insert(trans_,column_n,[column_1],axis= 1)

column_2 = np.array([35.8,12.0])
column_n = arr.shape[1]+2 # la ultima columna
trans_ = np.insert(trans_,column_n,[column_2],axis= 1)

print(trans_)

[[37.1   1.33 30.   70.2 ]
 [-3.6   4.5  10.7   0.5 ]]


[[37.1   1.33 30.   70.2  35.8  10.8 ]
 [-3.6   4.5  10.7   0.5  12.    3.  ]]


## Parte 2: Exploración y Minería de Datos:

Con el dataset nucleospoblacion.csv adjunto al laboratorio,
luego responda las siguientes preguntas usando pandas y
matplotlib.

In [95]:
import numpy as np
import random
import pandas as pd

In [97]:
df = pd.read_csv ('NucleosPoblacion.csv')
print(df)

     FID  OBJECTID                           Texto  Poblacion  CodMun  \
0      0         1                         Agüimes    29431.0   35002   
1      1         2                         Antigua    10458.0   35003   
2      2         3                        Arrecife    58156.0   35004   
3      3         4                          Arucas    36745.0   35006   
4      4         5                          Gáldar    24473.0   35009   
..   ...       ...                             ...        ...     ...   
847  847       848             Infante Juan Manuel    14192.0   30030   
848  848       849           Santa Maria de Gracia    13349.0   30030   
849  849       850                    Vista Alegre    15208.0   30030   
850  850       851  Poligono Sta M de Benquerencia    19177.0   45168   
851  851       852                            Grao    16367.0   12040   

                                      Municipio  CodProvin  \
0                                       Agüimes         35   

### EJERCICIO No.1 

¿Cuántos Municipios tienen más de 100000 habitantes?.

In [104]:
df_1 = df[df['Poblacion'] > 100000]
df_1.head()

print(f"hay {df_1.shape[0]} municipios que tienen mas de 100000 habitantes")

hay 62 municipios que tienen mas de 100000 habitantes


### EJERCICIO No.2 

Realice una gráfica de barras sobre la población de cada
ciudad, ordenela de menor a mayo y responda:
a. ¿Cuál es la segunda ciudad más poblada?
b. ¿Qué posición ocupa Granada en el ranking de
las ciudades más pobladas?

In [ ]:
plt.hist(sample_data)